version: '3.8'

services:
api:
  build: .
  container_name: api
  ports:
    - "3000:3000"

  environment:
    - MONGO_URI=mongodb://mongodb:27017/bookdb
    - PORT=3000
  depends_on:
  - mongo

mongodb:
  image: mongo:4.4
  container_name: mongodb
  ports:
  - "27017:27017"
  volumes:
  - mongo-data:data/db
volumes:
  mongo-data: